spring.application.name=RealTimeCache

spring.security.user.name=user
spring.security.user.password=icetruong

spring.datasource.url=jdbc:postgresql://localhost:5432/realtimecache
spring.datasource.username=postgres
spring.datasource.password=123456

security.jwt.secret=g3gnS9i8Vwb0W2Wt9xdYtKemYx7fbBcSu6E7f1AW6bg=
security.jwt.expiration-ms=108000000
