spring.application.name=RealTimeCache

spring.security.user.name=user
spring.security.user.password=icetruong

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/realtimecache}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

security.jwt.secret=g3gnS9i8Vwb0W2Wt9xdYtKemYx7fbBcSu6E7f1AW6bg=
security.jwt.expiration-ms=108000000
