spring.application.name=RealTimeCache

spring.security.user.name=user
spring.security.user.password=icetruong

spring.datasource.url=jdbc:postgresql://localhost:5432/realtimecache
spring.datasource.username=postgres
spring.datasource.password=123456

